apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-app-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo-app-frontend
  template: 
    metadata:
      labels:
        app: react-todo-app-frontend
    spec:
      containers:
      - name: react-todo-app-frontend
        image: dirudeen/react-todo-app_frontend:v32
        ports:
          - containerPort: 3000
        